#!/bin/sh
# provision this machine
set -eu

echob() {
	echo "$(tput bold)${1}$(tput sgr0)"
}

echob "Install apt packages and sources"

"$(dirname "$0")/add-apt-source"\
	"docker"\
	"https://download.docker.com/linux/ubuntu/gpg"\
  "https://download.docker.com/linux/ubuntu"\
  "$(lsb_release -cs)"\
	"stable"

"$(dirname "$0")/add-apt-source"\
	"azure-cli"\
	"https://packages.microsoft.com/keys/microsoft.asc"\
  "https://packages.microsoft.com/repos/azure-cli"\
  "$(lsb_release -cs)"\
	"main"

"$(dirname "$0")/add-apt-source"\
	"nodesource"\
	"https://deb.nodesource.com/gpgkey/nodesource.gpg.key"\
  "https://deb.nodesource.com/node_18.x"\
  "$(lsb_release -cs)"\
	"main"

"$(dirname "$0")/add-apt-source"\
	"fullstaq-ruby"\
	"https://raw.githubusercontent.com/fullstaq-labs/fullstaq-ruby-server-edition/main/fullstaq-ruby.asc"\
  "https://apt.fullstaqruby.org"\
  "ubuntu-$(lsb_release -rs)"\
	"main"

sudo apt update

sudo apt install\
	audacity\
	asciinema\
	azure-cli\
	borgmatic\
	brotli\
	build-essential\
	curl\
	direnv\
	docker-ce\
	docker-compose-plugin\
	exa\
	fd-find\
	ffmpeg\
	fish\
	fullstaq-ruby-3.2\
	fullstaq-ruby-common\
	fzf\
	git-lfs\
	git\
	gnome-boxes\
	gnupg-agent\
	gnupg2\
	golang\
	htop\
	inkscape\
	jq\
	kitty\
	leiningen\
	libasound2-dev\
	libdbus-1-dev\
	libheif-dev\
	libpq-dev\
	libsqlite3-dev\
	libssl-dev\
	libvips-dev\
	libvpx7\
	manpages-dev\
	mpv\
	neofetch\
	nextcloud-desktop\
	nodejs\
	pandoc\
	pdftk\
	pgcli\
	piper\
	ragel\
	ripgrep\
	shellcheck\
	tig\
	tmux\
	unzip\
	vim\
	wl-clipboard\
	woff2\
	yt-dlp

echob "Install snap packages"

sudo snap install 1password
sudo snap install chromium
sudo snap install deno
sudo snap install firefox
sudo snap install thunderbird
sudo snap install zoom-client

echob "Link dotfiles"

"$(dirname "$0")/link-dotfiles" /home/"$USER"/Code/dotfiles/tilde/*

echob "Switch to Fish"

"$(dirname "$0")/change-shell" "/usr/bin/fish"

echob "Add to docker group"

"$(dirname "$0")/add-to-groups" docker

echob "Set Ruby version and install gems"

rbenv global 3.2 && echo "Ruby Version set to 3.2"

for gem_name in amazing_print brakeman pry rails rubocop rspec
do
	if gem list --local | grep -E "^$gem_name " > /dev/null
	then
		gem update -q "$gem_name"
	else
		gem install -q "$gem_name"
	fi
done

echob "Install Go packages"

go install golang.org/x/lint/golint@latest && echo "golint installed"
go install golang.org/x/tools/gopls@latest && echo "gopls installed"
go install honnef.co/go/tools/cmd/staticcheck@latest && echo "staticcheck installed"
go install github.com/go-delve/delve/cmd/dlv@latest && echo "delve installed"

echob "Install Rust and Rust packages"

if [ "$(type rustup)" ]
then
	echo "rustup already installed"
else
	curl https://sh.rustup.rs -sSf | sh
fi

cargo install git-delta --locked
cargo install spotify_player --locked --no-default-features --features streaming,pulseaudio-backend,media-control

