#!/bin/sh
# provision this macOS machine
set -eu

echob() {
	echo "$(tput bold)${1}$(tput sgr0)"
}

echob "Link dotfiles"

"$(dirname "$0")/link-dotfiles" "$HOME"/Code/dotfiles/tilde/*

echob "Install brew packages"

brew bundle install\
	--file ~/.config/Brewfile\
	--no-lock\
	--cleanup

echob "Switch to Fish"

if grep -q fish /etc/shells; then
	echo "fish already added as a valid shell"
else
	echo "Adding fish as a valid shell"
	echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
fi

"$(dirname "$0")/change-shell" "/usr/local/bin/fish"

echob "Setup Docker Compose as a Docker Plugin"

mkdir -p ~/.docker/cli-plugins
ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

echob "Install Go packages"

go install golang.org/x/lint/golint@latest && echo "golint installed"
go install golang.org/x/tools/gopls@latest && echo "gopls installed"
go install honnef.co/go/tools/cmd/staticcheck@latest && echo "staticcheck installed"
go install github.com/go-delve/delve/cmd/dlv@latest && echo "delve installed"
