#!/bin/sh
# provision this Ubuntu machine
set -eu

echob() {
	echo "$(tput bold)${1}$(tput sgr0)"
}

echob "Install apt packages and sources"

codename=$(lsb_release -cs)
release=$(lsb_release -rs)

"$(dirname "$0")/add-apt-source"\
	"docker"\
  "https://download.docker.com/linux/ubuntu $codename stable"\
	"https://download.docker.com/linux/ubuntu/gpg"

"$(dirname "$0")/add-apt-source"\
	"nodesource"\
  "https://deb.nodesource.com/node_18.x $codename main"\
	"https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

"$(dirname "$0")/add-apt-source"\
	"fullstaq-ruby"\
  "https://apt.fullstaqruby.org ubuntu-$release main"\
	"https://raw.githubusercontent.com/fullstaq-labs/fullstaq-ruby-server-edition/main/fullstaq-ruby.asc"

"$(dirname "$0")/add-apt-source"\
	"heroku"\
  "https://cli-assets.heroku.com/apt ./"\
	"https://cli-assets.heroku.com/apt/release.key"

sudo apt update

sudo apt install\
	asciinema\
	audacity\
	borgmatic\
	brotli\
	build-essential\
	curl\
	direnv\
	docker-ce\
	docker-compose-plugin\
	dotnet-sdk-7.0\
	exa\
	ffmpeg\
	fish\
	flatpak\
	fullstaq-ruby-3.2\
	fullstaq-ruby-common\
	fzf\
	git-lfs\
	git\
	gnome-tweaks\
	gnupg-agent\
	gnupg2\
	graphviz\
	heroku\
	htop\
	inkscape\
	jq\
	kitty\
	leiningen\
	libasound2-dev\
	libdbus-1-dev\
	libheif-dev\
	libpq-dev\
	libsqlite3-dev\
	libssl-dev\
	libvips-dev\
	libvpx7\
	manpages-dev\
	mpv\
	neofetch\
	nextcloud-desktop\
	nodejs\
	pandoc\
	pdftk\
	pgcli\
	piper\
	plantuml\
	qalc\
	qutebrowser\
	ragel\
	ripgrep\
	scdaemon\
	shellcheck\
	tig\
	tmux\
	unzip\
	vim\
	wl-clipboard\
	woff2

echob "Install snap packages"

sudo snap install 1password
sudo snap install chromium
sudo snap install deno
sudo snap install firefox
sudo snap install thunderbird
sudo snap install zoom-client
sudo snap install libreoffice
sudo snap install --beta steam
sudo snap install ncspot
sudo snap install nvtop

echob "Install flatpak packages"

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub org.gnome.Boxes
flatpak install flathub org.gnome.Loupe

echob "Link dotfiles"

"$(dirname "$0")/link-dotfiles" /home/"$USER"/Code/dotfiles/tilde/*

echob "Enable systemd services"

systemctl --user enable backup-daily.timer backup-daily.service

echob "Switch to Fish"

"$(dirname "$0")/change-shell" "/usr/bin/fish"

echob "Add to docker group"

"$(dirname "$0")/add-to-groups" docker

echob "Set Ruby version and install gems"

rbenv global 3.2 && echo "Ruby Version set to 3.2"

gem install amazing_print brakeman pry rails rubocop rspec

echob "Install Go packages"

go install golang.org/x/lint/golint@latest && echo "golint installed"
go install golang.org/x/tools/gopls@latest && echo "gopls installed"
go install honnef.co/go/tools/cmd/staticcheck@latest && echo "staticcheck installed"
go install github.com/go-delve/delve/cmd/dlv@latest && echo "delve installed"

echob "Install Rust and Rust packages"

if [ "$(type rustup)" ]
then
	echo "rustup already installed"
else
	curl https://sh.rustup.rs -sSf | sh
fi

cargo install git-delta --locked

