#!/bin/sh
# provision this macOS machine
set -eu

echob() {
	echo "$(tput bold)${1}$(tput sgr0)"
}

echob "Link dotfiles"

"$(dirname "$0")/link-dotfiles" "$HOME"/Code/dotfiles/tilde/*

echob "Install brew packages"

brew bundle install\
	--file ~/.config/Brewfile\
	--no-lock\
	--cleanup

echob "Switch to Fish"

"$(dirname "$0")/change-shell" "/usr/local/bin/fish"

echob "Setup Docker Compose as a Docker Plugin"

mkdir -p ~/.docker/cli-plugins
ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
