#!/usr/bin/env fish
# better git branch view
# inspired by destroy all software

set -l PREFIX "%(HEAD)"
set -l REF "%(color:red)%(color:bold)%(refname:short)%(color:reset)"
set -l HASH "%(color:yellow)%(objectname:short)%(color:reset)"
set -l DATE "%(color:green)(%(committerdate:relative))%(color:reset)"
set -l AUTHOR "%(color:blue)%(color:bold)<%(authorname)>%(color:reset)"
set -l CONTENTS "%(contents:subject)"

set -l FORMAT "$PREFIX $REF $HASH $DATE $AUTHOR $CONTENTS"

# set -l extract_branch "sed 's/^*//' | awk '{print \$1;}'"

set -l enter_cmd "echo {} | git switch (sed 's/^*//' | awk '{print \$1;}')"

set -l opts "
  --ansi
  --bind=\"enter:execute($enter_cmd)+accept\"
"

git branch -v --color=always --format="$FORMAT" $argv |
  FZF_DEFAULT_OPTS="$opts" fzf
