#!/usr/bin/env fish
argparse "h/help" -- $argv
or exit

if set -q _flag_help
	echo "Clone a git repository, or if it already exists, pull it"
	echo "gcp <repository> <directory>"
	echo " -h/--help Show this message"
	exit
end

if test -d $argv[2]
	cd $argv[2]
	if test (git remote get-url origin) != $argv[1]
		echo "Wrong remote set" && exit 1
	end
	echo (basename "$PWD") (git pull)
else
	git clone $argv[1] $argv[2]
end
