" === General Setup ===
set noswapfile         " I don't like Swapfiles
set spell              " Activate spell checking
colorscheme solarized8 " solarized light

" === fzf ===
set rtp+=~/.fzf

" === netrw ===
let g:netrw_banner=0   " disable banner

" === ale ===
" the cats are back in town
let g:ale_sign_column_always = 1
let g:ale_sign_error="🙀"
let g:ale_sign_warning="😿"
let g:ale_sign_info="😼"
let g:ale_sign_style_error="🙀"
let g:ale_sign_style_warning="😿"

" clear background colors for the gutter
highlight clear ALEErrorSign
highlight clear ALEWarningSign

" do not highlight errors, just show the cats
let g:ale_set_highlights = 0

" fix problems when saving
let g:ale_fix_on_save=1
let g:ale_fixers = {
\   'javascript': ['prettier'],
\}

" === Mappings ===
" Fuzzy Finder with Ctrl+P
nnoremap <C-p> :<C-u>FZF<cr>
