# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="moonglum"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Necessary
alias please='sudo'

# One-letter shortcuts
alias o='open'
alias m='make'
alias g='bundle exec guard'
alias b='bundle'

# Open files with Mac OS X applications
alias chrome="open -a \"Google Chrome\""
alias safari="open -a Safari"
alias marked="open -a Marked"
alias pm="open -a Pixelmator"

# Reload zshrc
alias src="source ~/.zshrc"

# Copy output of last command to clipboard
alias copy_to_pastebord="fc -e - | pbcopy"

# Get current public IP
alias ip="curl icanhazip.com"

# Fix for REPLs and Editors without Readline
alias csi='rlwrap csi '

# Github-flavored Git
alias git=hub

# Manuals for Ruby People
alias man="gem man -s"

# Use vim as default editor – git for example
export EDITOR='vim'

# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# The same for tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Home
PATH=$PATH:$HOME/.bin

# Add RVM to PATH
PATH=$PATH:$HOME/.rvm/bin

# For homebrew
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH

# For LaTeX
PATH=/usr/texbin:$PATH

# For Cabal
PATH=/Users/moonglum/.cabal/bin:$PATH

# For NPM
PATH=/usr/local/share/npm/bin:$PATH

# ArangoDB Development
alias 'arangod-1.2.0'='arangod -c /usr/local/Cellar/arangodb/1.2.0/etc/arangodb/arangod.conf'

function arangod-devel {
  mkdir /tmp/arangodb-1.2
  cd ~/Code/arangodb
  ./bin/arangod /tmp/arangodb-1.2
}

function arango-rebuild {
  cd ~/Code/arangodb
  git pull
  make clean
  make setup
  make setup
  ./configure --enable-all-in-one-v8 --enable-all-in-one-libev --enable-all-in-one-icu --enable-relative
  make -j4
}

# Ruby Development
function current-version {
  gem list -r $1$
}

# iTunes Control
alias play='osascript -e "tell application \"iTunes\" to play"'
alias pause='osascript -e "tell application \"iTunes\" to pause"'

# For my code directory
alias c='nocorrect c'
c() { cd ~/Code/$1; }
_c() { _files -W ~/Code -/; }
compdef _c c
