#!/bin/sh
# Show the current battery status

# Check if there is a battery
if test -d /sys/class/power_supply/BAT0
then
  symbol="🔌"

  status=$(cat /sys/class/power_supply/BAT0/status)

  if test "$status" = "Discharging"
  then
    symbol="🔋"
  fi

  capacity=$(cat /sys/class/power_supply/BAT0/capacity)

  echo "$symbol $capacity%"
fi
