#!/bin/sh
# Show the current battery status, requires gawk

symbol="🔌"

if acpitool | grep -q 'off-line'
then
  symbol="🔋"
fi

percentage=$(acpitool | gawk 'match($0, /Battery.+:[^0-9]+([0-9]+)/, a) { print a[1] }')

if test -n "$percentage"
then
  echo "$symbol $percentage%"
fi
