#!/bin/sh
# provision the machine (GUI part)
set -eu

highlight=$(tput bold)
reset=$(tput sgr0)
echob() {
	echo "${highlight}${1}${reset}"
}

echob "Set keybindings to emacs"
gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"

# https://askubuntu.com/questions/979732/how-can-i-hide-the-dock-in-gnome#979756
echob "Hide Dock"
gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false

echob "Install apt packages"

sudo apt install\
	audacity\
	flatpak\
	gnome-boxes\
	kitty\
	mpv\
	nextcloud-desktop\
	piper

echob "Install snap packages"

sudo snap refresh

sudo snap install 1password
sudo snap install thunderbird

echob "Setup flatpak"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echob "Install flatpak packages"

flatpak install flathub\
	com.github.tchx84.Flatseal\
	com.github.maoschanz.drawing\
	com.obsproject.Studio\
	org.gnome.World.PikaBackup\
	org.inkscape.Inkscape\
	re.sonny.Tangram\
	us.zoom.Zoom
