#!/bin/sh
# provision this machine
set -eu

highlight=$(tput bold)
reset=$(tput sgr0)
echob() {
	echo "${highlight}${1}${reset}"
}

echob "Install apt packages"

if [ -f /etc/apt/sources.list.d/docker.list ]
then
	echo "Docker Repository already added"
else
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
	echo \
		"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
		$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

if [ -f /etc/apt/sources.list.d/azure-cli.list ]
then
	echo "azure-cli Repository already added"
else
	curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
	echo \
		"deb [arch=$(dpkg --print-architecture)] https://packages.microsoft.com/repos/azure-cli/ \
		$(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list > /dev/null
fi

if [ -f /etc/apt/sources.list.d/nodesource.list ]
then
	echo "nodesource Repository already added"
else
	curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/nodesource.gpg >/dev/null
	echo \
		"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x \
		$(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/nodesource.list > /dev/null
fi

if [ -f /etc/apt/sources.list.d/fullstaq-ruby.list ]
then
	echo "fullstaq-ruby Repository already added"
else
	curl -fsSL https://raw.githubusercontent.com/fullstaq-labs/fullstaq-ruby-server-edition/main/fullstaq-ruby.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/fullstaq.gpg > /dev/null
	echo \
		"deb [arch=$(dpkg --print-architecture)] https://apt.fullstaqruby.org \
		ubuntu-$(lsb_release -rs) main" | sudo tee /etc/apt/sources.list.d/fullstaq-ruby.list > /dev/null
fi

sudo apt update

sudo apt install\
	asciinema\
	azure-cli\
	brotli\
	build-essential\
	containerd.io\
	curl\
	direnv\
	docker-ce-cli\
	docker-ce\
	docker-compose-plugin\
	fd-find\
	ffmpeg\
	fish\
	flatpak\
	fullstaq-ruby-3.1\
	fullstaq-ruby-common\
	fzf\
	gawk\
	git-lfs\
	git\
	gnupg-agent\
	gnupg2\
	golang\
	htop\
	jq\
	libheif-dev\
	libpq-dev\
	libsqlite3-dev\
	libvips-dev\
	manpages-dev\
	neofetch\
	pandoc\
	nodejs\
	python3-pip\
	python3-gst-1.0\
	ragel\
	ripgrep\
	rust-all\
	shellcheck\
	tig\
	tmux\
	tree\
	unzip\
	woff2\
	vim

echob "Install snap packages"
sudo snap install chromium
sudo snap install firefox

echob "Setup flatpak"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echob "Install pip packages"

pip3 install --user pgcli
pip3 install --user yt-dlp

echob "Link dotfiles"

for file in /home/$USER/Code/dotfiles/tilde/*
do
	"$(dirname "$0")/ilns" "$file" "/home/$USER/.$(basename "$file")"
done

echob "Link scripts"

for file in /home/$USER/Code/dotfiles/exe/*
do
	sudo "$(dirname "$0")/ilns" "$file" "/usr/local/bin/$(basename "$file")"
done

echob "Switch to Fish"
desired_shell="/usr/bin/fish"
if [ "$SHELL" = "$desired_shell" ]
then
	echo "Shell is already set correctly"
else
	chsh -s "$desired_shell"
fi

echob "Install or Update Vim Plugins"

mkdir -p "/home/$USER/.vim/pack/bundle/start"
"$(dirname "$0")/gcp" "https://github.com/w0rp/ale" "/home/$USER/.vim/pack/bundle/start/ale"
"$(dirname "$0")/gcp" "https://github.com/editorconfig/editorconfig-vim" "/home/$USER/.vim/pack/bundle/start/editorconfig-vim"
"$(dirname "$0")/gcp" "https://github.com/junegunn/fzf" "/home/$USER/.vim/pack/bundle/start/fzf"
"$(dirname "$0")/gcp" "https://github.com/tpope/vim-commentary" "/home/$USER/.vim/pack/bundle/start/vim-commentary"
"$(dirname "$0")/gcp" "https://github.com/sheerun/vim-polyglot" "/home/$USER/.vim/pack/bundle/start/vim-polyglot"
"$(dirname "$0")/gcp" "https://github.com/tpope/vim-repeat" "/home/$USER/.vim/pack/bundle/start/vim-repeat"
"$(dirname "$0")/gcp" "https://github.com/tpope/vim-sensible" "/home/$USER/.vim/pack/bundle/start/vim-sensible"
"$(dirname "$0")/gcp" "https://github.com/altercation/vim-colors-solarized" "/home/$USER/.vim/pack/bundle/start/vim-colors-solarized"
"$(dirname "$0")/gcp" "https://github.com/tpope/vim-surround" "/home/$USER/.vim/pack/bundle/start/vim-surround"
"$(dirname "$0")/gcp" "https://github.com/skalnik/vim-vroom" "/home/$USER/.vim/pack/bundle/start/vim-vroom"

mkdir -p "/home/$USER/.vim/spell"
"$(dirname "$0")/ecurl" "http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl" "/home/$USER/.vim/spell/en.utf-8.spl"
"$(dirname "$0")/ecurl" "http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.sug" "/home/$USER/.vim/spell/en.utf-8.sug"
"$(dirname "$0")/ecurl" "http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.spl" "/home/$USER/.vim/spell/de.utf-8.spl"
"$(dirname "$0")/ecurl" "http://ftp.vim.org/pub/vim/runtime/spell/de.utf-8.sug" "/home/$USER/.vim/spell/de.utf-8.sug"

echob "Add to docker group"
if groups "$USER" | grep -q "docker"
then
	echo "Already in group docker"
else
	echo "Not in docker"
	sudo usermod -aG docker "$USER"
	echo "Added to group docker, will be active after logging in again"
fi

echob "Ruby"
rbenv global 3.1 && echo "Ruby Version set to 3.1"

for gem_name in amazing_print brakeman pry rails rubocop rspec
do
	if gem list --local | grep -E "^$gem_name " > /dev/null
	then
		echo "$gem_name already installed"
	else
		gem install "$gem_name"
	fi
done

echob "Go"
go install golang.org/x/lint/golint@latest && echo "golint installed"
go install golang.org/x/tools/gopls@latest && echo "gopls installed"
go install honnef.co/go/tools/cmd/staticcheck@latest && echo "staticcheck installed"

echob "Rust"
cargo install git-delta
