#!/bin/zsh
## run-rake-task-for-revision
# Pretty much what the name says
# from DAS

git checkout -q $2 &&
  bundle update --quiet &&
  bundle exec rake $1 |
  grep Finished |
  awk '{print $3}' |
  read time &&
  ((hashes = $time * 50)) &&
  echo "$rev `print-x-times $hashes '#'` $time"
